from pathlib import Path
from setuptools import find_packages, setup
import version

source_root = Path(".")
version = version.__version__

with (source_root / "README.md").open(encoding="utf-8") as f:
    long_description = f.read()

with (source_root / "requirements.txt").open(encoding="utf8") as f:
    requirements = f.readlines()

with open(source_root / "src/zarque_profiling/version.py", "w") as version_file:
    version_file.writelines([
        '""" This file is auto-generated by setup.py, please do not alter. """\n',
        f'__version__ = "{version}"\n',
        "",
    ])

setup(
    name="zarque-profiling",
    version=version,
    author="Crescendo Medix",
    author_email="g-ikeba@nifty.com",
    packages=find_packages("src"),
    package_dir={"": "src"},
    url="https://github.com/crescendo-medix/zarque-profiling",
    license="MIT",
    description="Data profiling tools for Big Data",
    python_requires=">=3.7, <3.12",
    install_requires=requirements,
    extras_require={
        "notebook": [
            "jupyter-client>=5.3.4",
            "jupyter-core>=4.6.3",
            "ipywidgets>=7.5.1",
        ],
        "unicode": [
            "tangled-up-in-unicode==0.2.0",
        ],
    },
    package_data={
        "zarque_profiling": ["py.typed"],
    },
    include_package_data=True,
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "License :: OSI Approved :: MIT License",
        "Framework :: IPython",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    keywords="big-data polars pandas data-profiling eda data-science data-analysis python jupyter ipython",
    long_description=long_description,
    long_description_content_type="text/markdown",
    entry_points={
        "console_scripts": [
            "zarque_profiling = zarque_profiling.controller.console:main",
        ]
    },
    options={"bdist_wheel": {"universal": True}},
)
